FROM homeagent-ros2:humble

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      xvfb \
      imagemagick \
      x11-utils \
    && rm -rf /var/lib/apt/lists/*
